### ISSUE TITLE
Conflict in the class name

### ISSUE THREAD

**Issue by ssutar** [scalvert/ember-es6-class-codemod#21]
In some files the name of class is conflicting with the variables in the scope.

For example, the below code if the file name is `foo.js`,
```
import Foo from 'ember-foo-service/services/foo'

export default Foo.extend({ ... })
``` 
is transformed as
```
import Foo from 'ember-foo-service/services/foo'

class Foo extends Foo({ ... })
```
This is incorrect and would result in error

How do we handle this use case? 

1. Figure out the variables in the current scope. 
2. If there is a conflict with the generated class name 
  - Either use the containing folder name as a prefix to the class name. For example if the folder path is `bar-biz/foo.js` use `BarBizFoo` as class name
  - If the conflict is not resolved in the above step, we should error out (or put a warning)

**Comment by pzuraq** [comment]
I think another way we can address the large majority of cases here is by appending the type of the class to the name. We can do this based on filepath and whether or not the class is the default export.

For instance, in this case we would see that the path matches `**/services/**/*.js`, so we would change the default export to be `FooService`.

I personally think this is better from a DX perspective, otherwise we may have multiple class names that are the same (`FooController` and `FooRoute`, for instance). This makes the class harder to grep for, and in general can be confusing.

The downside here is if utility classes that are _not_ meant to be a main type exist in that subfolder, e.g. `/services/utils/some-helper-class.js`. Named exports wouldn't be an issue, but it is still possible that default exports will exist for utility classes.

**Comment by ssutar** [comment]
Fixed with - https://github.com/scalvert/ember-es6-class-codemod/pull/37
